// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOACb4RdUWDN8OsGzBeOMRV36L7WpbldA',
    appId: '1:503869843350:web:0503c9f992b7f095e8dfb7',
    messagingSenderId: '503869843350',
    projectId: 'estacao-geometrica-esp32',
    authDomain: 'estacao-geometrica-esp32.firebaseapp.com',
    databaseURL: 'https://estacao-geometrica-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacao-geometrica-esp32.firebasestorage.app',
    measurementId: 'G-8BWN0YHEQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJrOU_-CpG5B6A3oyOBqXCRSbzVY487M',
    appId: '1:503869843350:android:56cd40e56f5a0b07e8dfb7',
    messagingSenderId: '503869843350',
    projectId: 'estacao-geometrica-esp32',
    databaseURL: 'https://estacao-geometrica-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacao-geometrica-esp32.firebasestorage.app',
  );
}
